USE ROLE SYSADMIN;
CREATE OR REPLACE DATABASE OBSERVATORY;
CREATE OR REPLACE SCHEMA OBSERVATORY.AUDIT;

CREATE OR REPLACE STAGE OBSERVATORY.AUDIT.SENSITIVE_STAGE
  ENCRYPTION = (TYPE = SNOWFLAKE_SSE);

CREATE OR REPLACE TABLE OBSERVATORY.AUDIT.AUDIT_LOG (
  EVENT_ID STRING, TS_UTC TIMESTAMP_TZ, ACTOR STRING, ACTION STRING,
  OBJ_NAME STRING, OBJ_SIZE_BYTES NUMBER, OBJ_SHA256 STRING,
  OBJ_SOURCE_PATH STRING, DEST_TYPE STRING, DEST_IDENTIFIER STRING,
  POLICY_ID STRING, NO_TRAINING BOOLEAN, PRIVATE_VM_ONLY BOOLEAN
);

CREATE OR REPLACE ROLE OBSERVATORY_WRITER;
GRANT USAGE ON DATABASE OBSERVATORY TO ROLE OBSERVATORY_WRITER;
GRANT INSERT, SELECT ON TABLE OBSERVATORY.AUDIT.AUDIT_LOG TO ROLE OBSERVATORY_WRITER;
GRANT USAGE ON STAGE OBSERVATORY.AUDIT.SENSITIVE_STAGE TO ROLE OBSERVATORY_WRITER;
